apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend                                 # 2
spec:                                                # 3
  containers:
    - image: sentiment-analysis-frontend             # 4
      name: sa-frontend                              # 5
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80                          # 6