apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: gcr.io/pofc003/sentiment-analysis-frontend
      name: sa-frontend
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80