apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sa-webapp
  name: sa-webapp
spec:
  selector:
    matchLabels:
      app: sa-webapp
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
      - image: sentiment-analysis-webapp
        imagePullPolicy: IfNotPresent
        name: sa-webapp
        env:
          - name: SA_LOGIC_API_URL
            value: "http://10.104.213.196:5000"
        ports:
          - containerPort: 8080
        resources: {}