apiVersion: v1
kind: Service
metadata:
  labels:
    app: sa-logic-v2
  name: sa-logic-v2
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5000
  selector:
    app: sa-logic