apiVersion: v1
kind: Service
metadata:
  labels:
    app: sa-webapp
  name: sa-webapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-webapp